<?php $this->headTitle('Respuestas - Trivia'); ?>
<div class="row bg-title">
    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
        <h4 class="page-title">Trivias - Usuarios</h4>
    </div>
    <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
        <ol class="breadcrumb">
            <li><a href="<?php echo $this->url('backend'); ?>">Panel</a></li>
            <li class="active">Trivias</li>
        </ol>
    </div>
    <!-- /.col-lg-12 -->
</div>
<!-- .row -->
<?php echo $this->partial('mia-layout-elite/flash-messenger'); ?>
<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title">Usuarios</h3>
            <p class="text-muted m-b-20">Acontinuación tendras el listado de los usuarios que contestaron correctamente.</p>
            <table style="width: 100%;">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Email</th>
                    </tr>
                    <?php foreach($this->votes as $votes): ?>
                    <tr>
                        <td><?php echo $votes['firstname']; ?></td>
                        <td><?php echo $votes['lastname']; ?></td>
                        <td><?php echo $votes['email']; ?></td>
                    </tr>
                    <?php endforeach; ?>
                </thead>
            </table>
        </div>
    </div>
</div>
<!-- /.row -->